### ISSUE TITLE
Remove default whitelist

### ISSUE THREAD

**Issue by binaryfire** [alleyinteractive/options-importer#17]
Hi guys

Is there a way to remove the default whitelist? I'd like to only export and import the options I specify (no defaults).

Cheers

**Comment by mboynes** [comment]
Hi @binaryfire, yes, you can manipulate the default allowlist using [the `options_import_allowlist ` filter](https://github.com/alleyinteractive/options-importer/blob/d12a011d193025787d2fafcf2e63ae5481fa2d4f/class-wp-options-importer.php#L440-L445). If you were to return an empty array to that filter, nothing would be checked by default. The "default" option would still exist, but it would do nothing. Here's some code for your plugin or theme to get you started:

```php
add_filter( 'options_import_allowlist', '__return_empty_array' );
```

**Comment by binaryfire** [comment]
Great, thanks so much!
